### PR TITLE
b/182396604: Remove additional_bindings in test

### PR DESCRIPTION
**Pull request by nareddyt**
These are not needed for grpc-web support. See discussion in bug. @qiwzhang will also update the docs.

Signed-off-by: Teju Nareddy <nareddyt@google.com>

### CODE REVIEW

**Comment by qiwzhang** [comment]
I don't remember what exactly the reason why we need to add this additional_bindings for grpc_web now.  Does the proto descriptor file used in the integration_test have such additional_bindings?   If yes, can you update the proto descriptor files after the removal to make sure it will not break the grpc_web?

**Comment by nareddyt** [comment]
Yup, this PR also updates `tests/endpoints/bookstore_grpc/proto/api_descriptor.pb` to remove them. It seems to be working so far.

**Review by qiwzhang — APPROVED** [review]
OK, cool.  Thanks for testing it out

**Pull request merged**
