### PR TITLE
wip experiment

### PR DESCRIPTION
**Pull request by shuoyang2016**
[DO NOT SUBMIT] experiment

* Only need for building image.

### CODE REVIEW

**Comment by nareddyt** [comment]
/ok-to-test

Generated docker image will be towards the end of ESPv2-build job. It will say `apiproxy`. You can deploy that to GKE.

Feel free to make a PR with changes to [OWNERS](https://github.com/GoogleCloudPlatform/esp-v2/blob/master/OWNERS) so you can have CI run automatically.

**Comment by nareddyt** [comment]
gcr.io/cloudesf-testing/apiproxy:d2f2864f6c94a2ac41031f4ae20730d21580bfe1

TSAN is a flake, don't worry about it

**Comment by shuoyang2016** [comment]
@nareddyt Thank you. I found the image. I am wondering how do I trigger a rebuild and how do I know the image uri?

**Comment by nareddyt** [comment]
> @nareddyt Thank you. I found the image. I am wondering how do I trigger a rebuild and how do I know the image uri?

I updated https://github.com/GoogleCloudPlatform/esp-v2/blob/master/OWNERS with your username. You can trigger a rebuild by:
- Just pushing a new commit to this branch/PR
- Make a comment with any of these commands: https://prow.k8s.io/command-help. See the `/test` command

Image URI is in the logs for the `ESPv2-build` job. It will be in the form `gcr.io/cloudesf-testing/apiproxy:${SHA}.

**Pull request closed without merging**
