### PR TITLE
doc/comment fix

### PR DESCRIPTION
**Pull request by brucearctor**

### CODE REVIEW

**Comment by brucearctor** [comment]
@googlebot I signed it!

**Comment by brucearctor** [comment]
@googlebot I fixed it.

**Comment by brucearctor** [comment]
@googlebot I fixed it.

**Comment by brucearctor** [comment]
I am the only author, so not sure what else is needed from a signature perspective.  Please advise.

**Comment by brucearctor** [comment]
@googlebot I signed it!

**Comment by brucearctor** [comment]
@cla/google ???

**Comment by brucearctor** [comment]
@google-oss-robot -- CLA has been signed, what is missing?

**Comment by qiwzhang** [comment]
Not sure.   I will force merge for you.  Thanks.

**Comment by brucearctor** [comment]
@googlebot I signed it!

**Comment by brucearctor** [comment]
@qiwzhang -- thanks.  Looks likely was the email in git, believe updated, I guess will see next time.

**Pull request merged**
