### PR TITLE
[WIP] Make health check name configurable

### PR DESCRIPTION
**Pull request by dchakarwarti**
Making Autogenerated health check names configurable in ESPv2 to ensure easy overrides

### CODE REVIEW

**Comment by dchakarwarti** [comment]
/cc @nareddyt 

Hey Teju!

Can you please take a look at the changes?

The pre submit failures seems unrelated to the changes made. Do you have any suggestions on it?

Thanks!

**Review by nareddyt — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
