### PR TITLE
Update Go version to 1.20

### PR DESCRIPTION
**Pull request by gopkarthik**

### CODE REVIEW

**Comment by nareddyt** [comment]
Since you updated the `Dockerfile`, can you go ahead and build a new presubmit image?

https://github.com/GoogleCloudPlatform/esp-v2/blob/b7a5150037c19bd304d955edaff91d46605a4c2c/Makefile#L341-L346

```shell
make docker.build-prow
make dockerpush-prow
```

And then update the image in this repo? https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml#L13

Replace all instances of `gcr.io/cloudesf-testing/gcpproxy-prow:v20221128-v2.39.0-3-g66e00dec-master` with the new image, send us a PR.

**Comment by gopkarthik** [comment]
> Replace all instances of gcr.io/cloudesf-testing/gcpproxy-prow:v20221128-v2.39.0-3-g66e00dec-master with the new image, send us a PR.

Will do. 

@nareddyt can you merge this PR?  I don't have authorization to do so.

**Comment by nareddyt** [comment]
> > Replace all instances of gcr.io/cloudesf-testing/gcpproxy-prow:v20221128-v2.39.0-3-g66e00dec-master with the new image, send us a PR.
> 
> Will do.
> 
> @nareddyt can you merge this PR? I don't have authorization to do so.

Actually can you update the image first? I want to make sure the `ESPv2-presubmit` job passes with go 1.20. Need to double check there are no behavior changes on upgrade.

Currently I think the presubmit is still building it using go `1.18`.

**Comment by gopkarthik** [comment]
> Actually can you update the image first? I want to make sure the `ESPv2-presubmit` job passes with go 1.20. Need to double check there are no behavior changes on upgrade.

Makes sense. Created PR (https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1984) to update

**Comment by gopkarthik** [comment]
From the [ProwJob yaml](https://oss.gprow.dev/prowjob?prowjob=70fe1d03-a72a-4f3f-ac5f-bc12b96228bd), these tests seem to be using the latest `gcpproxy-prow` image: gcr.io/cloudesf-testing/gcpproxy-prow:v20230705-1b3141e0-master

**Review by nareddyt — APPROVED** [review]

**Review by nareddyt — APPROVED** [review]

**Pull request merged**
