### PR TITLE
Bump version to 2.49.0

### PR DESCRIPTION
**Pull request by gopkarthik**
New ESPv2 release.

### CODE REVIEW

**Review by TAOXUY — APPROVED** [review]

**Review by dchakarwarti — APPROVED** [review]

**Comment by gopkarthik** [comment]
@TAOXUY Shall we force merge this change into master? The test failures are not due to this PR 
- `ESPv2-anthos-cloud-run-e2e-anthos-cloud-run-http-bookstore` all test cases pass & it's log export that failed.
- `ESPv2-presubmit*` tests seem to be failing for a while now (#904, #910 ). Logs don't show any failed test case.

**Pull request merged**
