### PR TITLE
Remove unused metrics from logs_metrics proto

### PR DESCRIPTION
**Pull request by qiwzhang**
Signed-off-by: Wayne Zhang <qiwzhang@google.com>

Google ServiceManagement will remove these un-used metrics in the endpoint service config. 
Following metrics are removed by cl/328226068:

* serviceruntime.googleapis.com/api/producer/error_count
* serviceruntime.googleapis.com/api/producer/by_consumer/error_count
* serviceruntime.googleapis.com/api/consumer/error_count

* serviceruntime.googleapis.com/api/producer/top_request_count_by_consumer
* serviceruntime.googleapis.com/api/producer/top_request_sizes_by_consumer
* serviceruntime.googleapis.com/api/producer/top_response_sizes_by_consumer
* serviceruntime.googleapis.com/api/producer/streaming_request_message_counts
* serviceruntime.googleapis.com/api/producer/streaming_response_message_counts
* serviceruntime.googleapis.com/api/producer/streaming_durations
* serviceruntime.googleapis.com/api/producer/request_bytes
* serviceruntime.googleapis.com/api/producer/response_bytes

      - serviceruntime.googleapis.com/api/consumer/request_overhead_latencies
      - serviceruntime.googleapis.com/api/consumer/backend_latencies
 
      - serviceruntime.googleapis.com/api/consumer/top_request_count_by_end_user
      - serviceruntime.googleapis.com/api/consumer/top_request_count_by_end_user_country
      - serviceruntime.googleapis.com/api/consumer/top_request_count_by_referer
      - serviceruntime.googleapis.com/api/consumer/streaming_request_message_counts
      - serviceruntime.googleapis.com/api/consumer/streaming_response_message_counts
      - serviceruntime.googleapis.com/api/consumer/streaming_durations
      - serviceruntime.googleapis.com/api/consumer/request_bytes
      - serviceruntime.googleapis.com/api/consumer/response_bytes

This changes will:
* Remove it in our testdata/logs_metrics.pb.txt proto file.  
* Change integration tests to make sure the removed metrics are not generated.

### CODE REVIEW

**Comment by qiwzhang** [comment]
No,  actually. Envoy service_control filter will not send out these metrics.  That is why this PR change the integration test  verification code to verify the metrics were not generated.

service_config contains these log_metrics.  config_mgr even send these log_metrics over to Envoy.  Envoy will only send metrics specified in log_metrics.   Once  these metrics are removed in log_metrics,  Envoy will not send them any more

**Comment by nareddyt** [comment]
/test ESPv2-build

FYI you may need #297 as well for e2e tests to pass

**Pull request merged**
