### PR TITLE
Sync check response proto

### PR DESCRIPTION
**Pull request by nareddyt**
Low probability that any of these responses will occur, but let's keep it in sync.

Testing: unit tests

Signed-off-by: Teju Nareddy <nareddyt@google.com>

### CODE REVIEW

**Comment by qiwzhang** [comment]
Do we need to update googleapis SHA [here](https://github.com/GoogleCloudPlatform/esp-v2/blob/master/bazel/googleapis.bzl#L20)

**Comment by nareddyt** [comment]
No, I double checked and the proto hasn't changed in 7 months. We just need to support the new codes that we didn't support previously.

**Comment by qiwzhang** [comment]
I see.

**Pull request merged**
